version: '3'

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o dr-peste.exe

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./dr-peste.exe

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f dr-peste.exe
      - rm -rf data/*.db

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  init:
    desc: Initialize environment
    cmds:
      - powershell -Command "if (!(Test-Path .env)) { Copy-Item .env.example .env }"
      - echo Please edit .env file with your Discord bot token
      - powershell -Command "if (!(Test-Path ansible/inventory.yml)) { Copy-Item ansible/inventory.yml.example ansible/inventory.yml }"
      - powershell -Command "if (!(Test-Path ansible/group_vars/all.yml)) { Copy-Item ansible/group_vars/all.yml.example ansible/group_vars/all.yml }"
      - echo Please edit ansible/inventory.yml with your VPS info and ansible/group_vars/all.yml with your Discord token 